### ISSUE TITLE
Icons Missing

### ISSUE THREAD

**Issue by Greenlark-zz** [DataAnalyticsinStudentHands/CommunityHealthWorkersApp#20]
When I start up the CHW app it shows me this... Am I the only one who has this?
![screenshot 5](https://cloud.githubusercontent.com/assets/5360172/7099151/9b255d28-dfb2-11e4-8823-e3ee024c8a06.png)

**Comment by CarlSteven** [comment]
I don't see this, but I think a quick `bower install` may help your issue. I've usually seen this when ionic was not properly installed or it wasn't able to access the ionicons.

**Comment by CarlSteven** [comment]
Also, just remembered, if you look at the console, and then refresh the page, you may see that it's getting 404s on some files. That could help you pinpoint the issue.

**Comment by Greenlark-zz** [comment]
ok, some of the icons are back but I also have your problem were it has those double circle icons

**Comment by CarlSteven** [comment]
I just pushed, that should fix that double circle icon.

**Comment by Greenlark-zz** [comment]
Ya, just updated, its working. Just some icons still wont pop up so I will investigate that.

**Comment by CarlSteven** [comment]
Closing this because icons are showing up on HouSuggest version of CHWApp.

Link to latest: http:///housuggest.org/CHWAppTest
